/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of repos.
         * @description Returns the list of repositories stored in the database.
         */
        get: operations["getRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/fetch-repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch GitHub repos after login.
         * @description Fetches all GitHub repositories for the authenticated user's linked GitHub account and stores them in the database.
         */
        get: operations["fetchGithubRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of tasks.
         * @description Returns all tasks sorted by creation date descending.
         */
        get: operations["getTasks"];
        put?: never;
        /**
         * Create a task.
         * @description Creates a new task. Note: the task router does not currently enforce authentication middleware even though it is documented as requiring a session.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (MongoDB ObjectId). */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a task by id.
         * @description Returns a single task by its id.
         */
        get: operations["getTaskById"];
        put?: never;
        post?: never;
        /**
         * Delete a task.
         * @description Deletes a task by id and returns the deleted document.
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * Update a task.
         * @description Partially updates a task. At least one field is required. Note: the task router does not currently enforce authentication middleware.
         */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent activities.
         * @description Returns recent activities for the authenticated user.
         */
        get: operations["getRecentActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current user.
         * @description Signs out the current session via Better Auth.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user profile.
         * @description Returns the user profile for the authenticated user.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user profile.
         * @description Partially updates the authenticated user's profile. At least one field is required.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check.
         * @description Returns database connection status and process uptime.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            success: boolean;
            message: string;
            statusCode: number;
            /** Format: date-time */
            timestamp: string;
            data?: unknown;
        };
        Task: {
            _id?: string;
            title: string;
            description?: string;
            completed: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTaskInput: {
            title: string;
            description?: string;
            /** @default false */
            completed: boolean;
        };
        UpdateTaskInput: {
            title?: string;
            description?: string;
            completed?: boolean;
        };
        IndexingProgress: {
            /** @default 0 */
            filesProcessed: number;
            /** @default 0 */
            totalFiles: number;
        };
        Repo: {
            _id?: string;
            userId: string;
            githubRepoId: number;
            fullName: string;
            defaultBranch: string;
            private: boolean;
            language?: string | null;
            stars: number;
            /** @enum {string} */
            indexingStatus: "not_indexed" | "indexing" | "ready" | "failed";
            indexingProgress: components["schemas"]["IndexingProgress"];
            lastIndexedCommitSha?: string | null;
            /** Format: date-time */
            lastIndexedAt?: string | null;
            isOutdated: boolean;
            webhookId?: string | null;
            isActive: boolean;
            /** Format: date-time */
            deactivatedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Activity: {
            _id?: string;
            userId: string;
            repoId?: string | null;
            repository: string;
            action: string;
            detail?: string | null;
            /** @enum {string} */
            tone: "green" | "cyan" | "amber" | "red" | "muted";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        IndexedRepo: {
            repoId: number;
            fullName: string;
            defaultBranch: string;
            wikiEnabled: boolean;
            /** @enum {string} */
            status: "pending" | "indexing" | "indexed" | "failed";
            vectorNamespace: string;
            /** Format: date-time */
            lastIndexedAt?: string;
        };
        UserProfile: {
            _id?: string;
            authUserId: string;
            githubUsername: string;
            /** Format: email */
            email: string;
            avatarUrl?: string;
            indexedRepos: components["schemas"]["IndexedRepo"][];
            installationId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateUserInput: {
            githubUsername?: string;
            /** Format: email */
            email?: string;
            /** Format: uri */
            avatarUrl?: string | null;
            installationId?: number;
        };
        ErrorResponse: {
            success: boolean;
            message: string;
            errors?: unknown;
        };
        TaskResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Task"];
        };
        TaskListResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Task"][];
        };
        RepoListResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Repo"][];
        };
        ActivityListResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Activity"][];
        };
        UserProfileResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["UserProfile"];
        };
        LogoutResponse: components["schemas"]["ApiResponse"] & {
            data?: Record<string, never> | null;
        };
        HealthResponse: components["schemas"]["ApiResponse"] & {
            data?: {
                /** @enum {string} */
                databaseStatus: "disconnected" | "connected" | "connecting" | "disconnecting";
                uptime: number;
                message: string;
                timestamp: number;
            };
        };
    };
    responses: {
        /** @description Missing or invalid session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    fetchGithubRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The fetched and stored repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoListResponse"];
                };
            };
            /** @description GitHub account is not linked, or the user profile is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of tasks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskInput"];
            };
        };
        responses: {
            /** @description The created task. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTaskById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (MongoDB ObjectId). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Invalid task id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (MongoDB ObjectId). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Invalid task id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (MongoDB ObjectId). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskInput"];
            };
        };
        responses: {
            /** @description The updated task. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecentActivities: {
        parameters: {
            query?: {
                /** @description Maximum number of activities to return (1-200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of recent activities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description User profile not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInput"];
            };
        };
        responses: {
            /** @description The updated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description User profile not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
